name: Build and test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: practical-scheme/setup-gauche@v6
      with:
        prebuilt-binary: true
    - name: Install dependencies
      run: |
        sudo apt install -yq libglu1-mesa-dev freeglut3-dev mesa-common-dev \
             libglew-dev libxmu-dev libxi-dev libglfw3-dev libvulkan-dev
    - name: Build and check
      run: |
        ./configure
        make
        make -s check
